name: campuslib
description: CampusLib Library Management System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.2
  google_fonts: ^6.2.1
  animate_do: ^3.3.4
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    # - assets/images/